# Site settings
title: IABC Lab
description: "Design for Individual, Art, Business and Computation"
url: "https://jingliao132.github.io"




# Secondary Parameters
baseurl: "/IABC-lab"
header-img: img/home-bg.jpg
headercolor: "#FFFFFF"
logo: /IABC-lab/img/logos/Project-Pages-New-Logo-Inverted.png
read_more: "disabled"
teaser:  # filename of teaser fallback teaser image placed in /images/, .e.g. "500x300.png"

# Tertiary Parameters
github_username:  jingliao132 #projectpages
project_repository: IABC-lab #project-pages
disqus_shortname: IABC-lab #project-pages
g-analytics: UA-75881392-1
altmetric: true

# Build settings
gems: [jekyll-paginate]
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

collections:
  publications:
    output: true
    permalink: /:collection/:path/
  projects:
    output: true
    permalink: /:collection/:path/
    
# Jekyll Settings

defaults:
  # projects
  - scope:
      path: "projects"
      type: "pages"
    values:
      layout: "project"
      header-img: "img/home-bg.jpg"
  
  # _posts
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      header-img: "img/home-bg.jpg"
      
  # _publications
  - scope:
      path: ""
      type: "publications"
    values:
      layout: "publication"
      header-img: "img/home-bg.jpg"

# Prose Settings
prose:
  ignore: ['feed.xml', '/stl', '/js', '/plugin', '/lib', '/projectors', '_layouts', '/_includes', 'Gruntfile.js', 'package.json', 'proselinks.jsonp', 'ppanchor.matin', '.gitignore', '/search', '/css', '/img', 'favicon.png','_data/*.json','LICENSES.md','README.md','colorscheme.scss','members.html','mentions.html','index.html']
  siteurl: 'http://jingliao132.github.io/IABC-lab/'
  ispp: true
  media: 'img'
  metadata:
    projects:
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "description"
        field:
          element: "text"
          label: "Description"
          value: ""
      - name: "category"
        field:
          element: "text"
          label: "Project"
          value: "" 
          
    _publications:
      - name: "layout"
        field:
          element: "select"
          label: "Choose Layout"
          placeholder: "Layouts"
          options:
            - name: "Post"
              value: "post"
            - name: "Slide"
              value: "slide"
            - name: "Projector"
              value: "projector"
            - name: "Notebook"
              value: "notebook"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "author"
        field:
          element: "text"
          label: "Author"
          value: ""
      - name: "tags"
        field:
          element: "text"
          label: "Tags (seperate with whitespace)"
          value: ""
      - name: "category"
        field:
          element: "text"
          label: "Publication"
          value: ""  
      - name: "excerpt"
        field:
          element: "text"
          label: "Excerpt"
          value: ""
      - name: "paperurl"
        field:
          element: "text"
          label: "Paperurl"
          value: ""
      - name: "citation"
        field:
          element: "text"
          label: "Citation"
          value: ""
         
    _posts:
      - name: "subtitle"
        field:
          element: "text"
          label: "Sub-Title (Short Description)"
          value: ""
      - name: "layout"
        field:
          element: "select"
          label: "Choose Layout"
          placeholder: "Layouts"
          options:
            - name: "Post"
              value: "post"
            - name: "Slide"
              value: "slide"
            - name: "Projector"
              value: "projector"
            - name: "Notebook"
              value: "notebook"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "author"
        field:
          element: "text"
          label: "Author"
          value: ""
      - name: "tags"
        field:
          element: "text"
          label: "Tags (seperate with whitespace)"
          value: ""
      - name: "category"
        field:
          element: "text"
          label: "Project"
          value: ""    
      - name: "horizontal"
        field:
          element: "hidden"
          value: </section></section><section markdown="1" data-background="http://jingliao132.github.io/IABC-lab/img/slidebackground.png"><section markdown="1">
      - name: "vertical"
        field:
          element: "hidden"
          value: </section><section markdown="1">
      - name: "slideinit"
        field:
          element: "hidden"
          value: <section markdown="1" data-background="http://jingliao132.github.io/IABC-lab/img/slidebackground.png"><section markdown="1">
      - name: "theme"
        field:
          element: "select"
          label: "Theme (Slide)"
          placeholder: "Theme (Slide)"
          options:
            - name: "Beige"
              value: "beige"
            - name: "Blood"
              value: "blood"
            - name: "Moon"
              value: "moon"          
            - name: "Night"
              value: "night"
            - name: "Sky"
              value: "sky"
            - name: "Solarized"
              value: "solarized"             
      - name: "trans"
        field:
          element: "select"
          label: "Transition (Slide)"
          placeholder: "Transition (Slide)"
          options:
            - name: "Cube"
              value: "cube"
            - name: "Page"
              value: "page"
            - name: "Concave"
              value: "concave"          
            - name: "Linear"
              value: "linear"
            - name: "Fade"
              value: "fade"
            - name: "None"
              value: "none"             
      - name: "visualworkflow"
        field:
          element: "checkbox"
          label: "Visual Workflow Chart (Some Layouts)"
          value: "true"
